openapi: 3.0.0
info:
  version: "1.0.0"
  title: ServiceB
paths:
  /echo:
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '402':
          description: Forbidden
        '403':
          description: Not Found
  /health:
    get:
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '402':
          description: Forbidden
        '403':
          description: Not Found